//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class aanvullenderelatieinformatie
    {
        public int aanvullenderelatieinformatieid { get; set; }
        public int relatieid { get; set; }
        public int relatieinformatietypeid { get; set; }
        public string relatieinformatie { get; set; }
        public Nullable<System.DateTime> van { get; set; }
        public Nullable<System.DateTime> tot { get; set; }
        public string datumPrecisie { get; set; }
        public System.DateTime gewijzigdOp { get; set; }
    
        public virtual relatie relatie { get; set; }
        public virtual relatieinformatietype relatieinformatietype { get; set; }
    }
}
