//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class meestvoorkomendenaman
    {
        public int statestiekid { get; set; }
        public int stamboomid { get; set; }
        public string naam { get; set; }
        public bool naamsoort { get; set; }
    
        public virtual stamboom stamboom { get; set; }
    }
}
