//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeninstamboom
    {
        public int persooninstamboomid { get; set; }
        public int stamboomid { get; set; }
        public int persoonid { get; set; }
        public int kekuleid { get; set; }
    
        public virtual persoon persoon { get; set; }
        public virtual stamboom stamboom { get; set; }
    }
}
