//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class persoonhistorie
    {
        public int persoonhistorieid { get; set; }
        public int persoonid { get; set; }
        public System.DateTime gewijzigdop { get; set; }
        public string voornaam { get; set; }
        public string overigenamen { get; set; }
        public string tussenvoegsel { get; set; }
        public string achternaam { get; set; }
        public string achtervoegsel { get; set; }
        public string geboortenaam { get; set; }
        public string geslacht { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> geboortedatum { get; set; }
        public string geboorteprecisie { get; set; }
        public Nullable<System.DateTime> geboortedatum2 { get; set; }
        public string geboorteplaats { get; set; }
        public string adress { get; set; }
        public string beroep { get; set; }
    
        public virtual persoon persoon { get; set; }
    }
}
