//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class relatiehistorie
    {
        public int relatiehistorieid { get; set; }
        public int relatieid { get; set; }
        public System.DateTime gewijzigdop { get; set; }
        public int persoonid1 { get; set; }
        public int relatietypeid { get; set; }
        public int persoonid2 { get; set; }
    
        public virtual relatie relatie { get; set; }
    }
}
