//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbInitio.Web.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class stamboomtoegang
    {
        public int stamboomaccountid { get; set; }
        public int accountid { get; set; }
        public int stamboomid { get; set; }
        public int stamboomRechten { get; set; }
    
        public virtual account account { get; set; }
        public virtual stamboom stamboom { get; set; }
    }
}
